### ISSUE TITLE
Peer-to-peer: to-do list 

### ISSUE THREAD

**Issue by ha-manel** [mavericks-db/todo-list#4]
## Hi @mavericks-db,

Great job on creating a good looking to-do list 👍🏻 💯 
✔️ Good styling.
✔️ Your to-do list's functionalities are smooth.
✔️ Your project has smooth interactions with the user ✨ 

Here are some of the improvements your team has suggested:
- We noticed that you use `localStorage.clear()` every time you want to override the existing entry in localStorage. The local storage overrides the existing entries automatically when you set a new value with the same key. So it's better to remove the `localStorage.clear()` lines to optimize your code.
- We noticed that some of your logic is split between multiple files. Please consider reconstructing your modules because `index.js` and `status.js` are almost empty and have no particular functionality.
- We suggest removing the `e.preventDefault()` on the input's event handler since it's not a form and it doesn't have an undesirable default behavior.

**Comment by mavericksbalitaan** [comment]
Hi there! Thanks for the review. 👍  I have done some immediate changes ♻️  and replaced the alert message with a custom one. Here is my latest commit: https://github.com/mavericks-db/todo-list/commit/f035a845b1e0def2e75196ad0a297ea9ba3b6dee
I'm in the process of reconstructing the modules and hopefully optimizing my code. Have a good day! 😃
